version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - sqlite-web
    environment:
      MONGO_URL: "mongodb://admin:password@mongodb:27017/"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  sqlite-web:
    image: coleifer/sqlite-web:latest
    container_name: sqlite-web
    ports:
      - "8080:8080"
    volumes:
      - sqlite_data:/data
    command: ["sqlite_web", "/data/mydatabase.db"]


volumes:
  sqlite_data:
#   mosquitto_data:
#   mosquitto_log:
