# Use official Python image
FROM python:3.10

# Install required OS libraries for OpenCV
RUN apt-get update && apt-get install -y libgl1 libglib2.0-0

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application files
COPY . .

# Expose the port FastAPI will run on
EXPOSE 8000

# Set Python path
ENV PYTHONPATH=/app

# Run FastAPI server
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
